---
title: Users Guide
---

This document replicates the [Users guide](../users_guide.qmd), except that it's using
owlplanner live.

## An example of Owl's functionality

With about 10 lines of Python code, one can generate a full case study. Here is a typical plan with some comments.
A plan starts with the names of the individuals, their birth years and life expectancies, and a name for the plan.
Dollar amounts are in k\$ (i.e. thousands) and ratios in percentage.

```{python}
# Load owlplanner

import owlplanner as owl
```

### Participants

* Jack was born in 1962-07-04 and expects to live to age 89.
* Jill was born in 1965-12-01 and hopes to live to age 92.
* Plan starts on Jan 1st of the earliest year


```{python}

plan = owl.Plan(['Jack', 'Jill'], 
                ['1962-07-14', '1965-12-01'], 
                [89, 92], 
                'jack & jill - tutorial' )
```

### Assets

* Jack has $90.5k in a taxable investment account, $600.5k in a tax-deferred account and $70k from 2 tax-free accounts.
* Jill has $60.2k in her taxable account, $150k in a 403b, and $40k in a Roth IRA.

```{python}
plan.setAccountBalances(
        taxable=[90.5, 60.2],
        taxDeferred=[600.5, 150], 
        taxFree=[50.6 + 20, 40.8]
)
```

### Wages and Contributions

* An Excel file contains 2 tabs (one for Jill, one for Jack) describing anticipated wages and contributions.

```{python}
plan.readContributions('../../examples/jack+jill.xlsx')
```

### Asset allocations

Over their lifetime, Jack and Jill will want to reset their asset allocations.  

* Jack will glide an s-curve for asset allocations from a 60/40 -> 70/30  stocks/bonds portfolio.
* Jill will do the same thing but is a bit more conservative from 50/50 -> 70/30 stocks/bonds portfolio.

```{python}
plan.setInterpolationMethod('s-curve')
plan.setAllocationRatios('individual', 
        generic=[
          [[60, 40, 0, 0], [70, 30, 0, 0]], 
          [[50, 50, 0, 0], [70, 30, 0, 0]]]
)
```

### Pensions and Social Security

* Jack has no pension, but Jill will receive $10k per year at 65 yo.

```{python}
plan.setPension([0, 10.5], [65, 65])
```

* Jack anticipates receiving social security of $28.4k at age 70.
* Jill $19.7k at age 62. All values are in today's $.

```{python}
plan.setSocialSecurity([28.4, 19.7], [70, 62])
```

### Spending

* Instead of a 'flat' profile, we select a 'smile' spending profile, with 60% needs for the survivor.

```{python}
plan.setSpendingProfile('smile', 60)
```

### Rate Scenario

For this example, we will reproduce the historical sequence of returns starting in year 1969.

```{python}
plan.setRates('historical', 1969)
```

## Planning Goals

* Jack and Jill want to leave a bequest of $500k
* They want to limit Roth conversions to $100k per year.
* Jill's 403b plan does not support in-plan Roth conversions.

We solve for the maximum net spending profile under these constraints.

```{python}
plan.solve(
        'maxSpending', 
        options={
          'maxRothConversion': 100,
          'bequest': 500, 
          'noRothConversions': 'Jill'}
)
```

## Results

Once we set our goals and solve, OWL can tell us more about what's happening

The output can be seen using the following commands that display various plots of the decision variables in time.

### Net Spending

```{python}
plan.showNetSpending()
```

### Accounts and balances

```{python}
plan.showAccounts()
```

### Asset distributions

```{python}
plan.showAssetComposition()
```


By default, all these plots are in nominal dollars. To get values in today's $, a call to

```python
plan.setDefaultPlots('today')
```

would change all graphs to report in today's dollars. Each plot can also override the default by setting the `value`
parameters to either *nominal* or *today*, such as in the following example, which shows the taxable ordinary
income over the duration of the plan,
along with inflation-adjusted extrapolated tax brackets. Notice how the optimized income is surfing
the boundaries of tax brackets.

### Gross Income vs Tax Brackets

```{python}
plan.showGrossIncome(value='nominal')
```

### Optimal Spending Profile

The optimal spending profile is shown in the next plot (in today's dollars). Notice the drop
(recall we selected 60% survivor needs) at the passing of the first spouse.

```{python}
plan.showProfile('today')
```

### Account balances

The following plot shows the account balances in nominal value for all savings accounts owned by Jack and Jill.
It was generated using

```{python}
plan.showAccounts(value='nominal')
```

### Cash flows and sources

This plot shows the complex cash flow from all sources.

```{python}
plan.showSources(value='nominal')
```

### Tax liabilities

For taxes, the following call will display Medicare premiums (including Part B IRMAA fees) and federal income tax

```{python}
plan.showTaxes(value='nominal')
```

### Asset distributions

For the case at hand, recall that asset allocations were selected above through

```python
plan.setAllocationRatios('individual', generic=[[[60, 40, 0, 0], [70, 30, 0, 0]], [[50, 50, 0, 0], [70, 30, 0, 0]]])
```

Gliding from a 60%/40% stocks/bonds portfolio to 70%/30% for Jack, and 50%/50% -> 70%/30% for Jill.
Assets distribution in all accounts in today's $ over time can be displayed from

```{python}
plan.showAssetComposition(value='today')
```

### Rates

These plots are irregular because we used historical rates from 1969. The volatility of
the rates offers Roth conversion benefits which are exploited by the optimizer.
The rates used can be displayed by:

```{python}
plan.showRates()
```

#### Correlations

Values between brackets <> are the average values and volatility over the selected period. 

For the statisticians, rates distributions and correlations between them can be shown using:
```python
plan.showRatesCorrelations()
```

### Summary

A short text summary of the outcome of the optimization can be displayed through using:

```{python}
plan.summary()
```
The output of the last command reports that if future rates are exactly like those observed
starting from 1969 and the following years, Jack and Jill could afford an annual spending of
 \\$97k starting this year
(with a basis of \\$88.8k - the basis multiplies the profile which can vary over the course of the plan).
The summary also contains some details:

### Saving results

And an Excel workbook can be saved with all the detailed amounts over the years by using the following command:

```{python}
plan.saveWorkbook(overwrite=True)
```

