# docker/Dockerfile

FROM python:3.13-alpine

WORKDIR /app

RUN apk update; apk upgrade; apk add curl git bash

COPY buildentrypoint.sh /usr/bin/entrypoint.sh
COPY runentrypoint.sh /usr/bin/runentrypoint.sh

RUN chmod 555 /usr/bin/entrypoint.sh /usr/bin/runentrypoint.sh

EXPOSE 8501

HEALTHCHECK CMD curl --fail http://localhost:8501/_stcore/health

ENTRYPOINT ["/bin/bash", "/usr/bin/entrypoint.sh"]
