"Plan Name" = "john+sally"

["Basic Info"]
Status = "married"
Names = [ "John", "Sally",]
"Birth year" = [ 1962, 1962,]
"Life expectancy" = [ 92, 92,]
"Start date" = "01-01"

[Assets]
"taxable savings balances" = [ 200.0, 200.0,]
"tax-deferred savings balances" = [ 750.0, 750.0,]
"tax-free savings balances" = [ 50.0, 50.0,]
"Beneficiary fractions" = [ 1, 1, 1,]
"Spousal surplus deposit fraction" = 0.5

["Wages and Contributions"]
"Contributions file name" = "john+sally.xlsx"

["Fixed Income"]
"Pension amounts" = [ 0.0, 0.0,]
"Pension ages" = [ 65, 65,]
"Pension indexed" = [ false, false,]
"Social security amounts" = [ 36.0, 21.6,]
"Social security ages" = [ 67, 67,]

["Rates Selection"]
"Heirs rate on tax-deferred estate" = 30.0
"Long-term capital gain tax rate" = 15.0
"Dividend tax rate" = 2.0
"TCJA expiration year" = 2026
Method = "historical average"
From = 1990
To = 2023

["Asset Allocation"]
"Interpolation method" = "linear"
"Interpolation center" = 15
"Interpolation width" = 5
Type = "individual"
generic = [ [ [ 60, 40, 0, 0,], [ 60, 40, 0, 0,],], [ [ 60, 40, 0, 0,], [ 60, 40, 0, 0,],],]

["Optimization Parameters"]
"Spending profile" = "flat"
"Surviving spouse spending percent" = 60
Objective = "maxBequest"

["Solver Options"]
maxRothConversion = 200
netSpending = 100

[Results]
"Default plots" = "today"
