"""
Test that requirements.txt stays in sync with the uv lockfile.

`uv.lock` is the single source of truth for dependencies; `requirements.txt` is
a generated export (run `make requirements`). CI installs from the exported
file, so drift between the two means the tested dependency set is not the
locked one. This test fails the build whenever they disagree.

Copyright (C) 2024-2026 Martin-D. Lacasse and The Owl Authors

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""

import pathlib
import shutil
import subprocess

import pytest

_REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]

# Must match the `requirements` target in the Makefile.
_EXPORT_CMD = ["uv", "export", "--frozen", "--no-dev", "--no-hashes"]


def _body(text):
    """Return the pinned-dependency lines, dropping uv's autogenerated banner.

    The banner echoes the invoking command, which differs between writing to a
    file (`-o requirements.txt`) and capturing stdout, so it cannot be compared.
    Per-package `# via ...` annotations are indented and are kept.
    """
    lines = text.splitlines()
    start = 0
    for i, line in enumerate(lines):
        if not line.startswith("#"):
            start = i
            break
    return lines[start:]


@pytest.mark.skipif(shutil.which("uv") is None, reason="uv is not installed")
def test_requirements_matches_lockfile():
    result = subprocess.run(_EXPORT_CMD, cwd=_REPO_ROOT, capture_output=True, text=True)
    assert result.returncode == 0, (
        f"`{' '.join(_EXPORT_CMD)}` failed with exit code {result.returncode}. "
        f"uv.lock may be stale relative to pyproject.toml; run `make lock`.\n{result.stderr}"
    )

    expected = _body(result.stdout)
    actual = _body((_REPO_ROOT / "requirements.txt").read_text())

    missing = sorted(set(expected) - set(actual))
    extra = sorted(set(actual) - set(expected))
    assert expected == actual, (
        "requirements.txt is out of sync with uv.lock. Run `make requirements` to regenerate it.\n"
        f"  in lockfile but not in requirements.txt: {missing or 'none'}\n"
        f"  in requirements.txt but not in lockfile: {extra or 'none'}"
    )
